# Generated by Django 4.1.6 on 2023-03-26 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_post'),
        ('accounts', '0003_alter_account_commented_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='commented_posts',
            field=models.ManyToManyField(blank=True, related_name='commented_users', to='posts.post', verbose_name='Прокомментированные публикации'),
        ),
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='account',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_users', to='posts.post', verbose_name='Понравившиеся публикации'),
        ),
    ]
